//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public long OrderID { get; set; }
        public Nullable<long> Customer_ID { get; set; }
        public Nullable<int> Item_ID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual FoodItem FoodItem { get; set; }
    }
}
